### ISSUE TITLE
./sandwich.rb:68: syntax error, unexpected ')'

### ISSUE THREAD

**Issue by Ayush2108** [Lupin-Holmes/sandwich#1]
Hello Team,

I am using this script to generate UUIDv1 for the sandwich attack but I am facing synatx error while running this command
```
./sandwich.rb f39ed220-b41c-11ee-a08a-63c2beaaab0f 0242af40-b41d-11ee-a08a-63c2beaaab0f

```

![image](https://github.com/Lupin-Holmes/sandwich/assets/84571019/c6da4f4e-927b-4028-b3a7-2e55eb2d7f7f)

**Comment by thelilnix** [comment]
My solution for this issue:
- Go to line `68`, then remove the `:` character before the last `)`.
![Screenshot 2024-03-02 at 12 59 13](https://github.com/Lupin-Holmes/sandwich/assets/23361794/e5ad56eb-cf61-4bf5-89bc-35253c7fbbaf)

**Comment by ocarta-l** [comment]
Hi @Ayush2108,

Sorry for the late answer. 
Your issue is probably because you use a ruby version < 3

I will update the README to make it clear, as we don't plan to make it compatible to prior ruby versions 

Thanks for your feedback :)

**Comment by ocarta-l** [comment]
Done https://github.com/Lupin-Holmes/sandwich/commit/5cffcb8b950b4a2adce87dd16ce291aaf6258571 :)
